### PR TITLE
SFOS aarch64 fixes

### PR DESCRIPTION
**Pull request by Karry**
Necessary fixes for aarch64 build with recent SFOS SDK ( https://github.com/fredldotme/harbour-owncloud/issues/60 ). See commit messages for details.

### CODE REVIEW

**Comment by fredldotme** [comment]
LGTM, thanks!

Keep in mind though that I'm not possessing any aarch64-capable SfOS device right now. So it would be interesting to see if you're interested in distributing the application using a "blessed" account or something.

**Comment by Karry** [comment]
Hi. I published aarch64 build on [Openrepos](https://openrepos.net/content/karry/ghostcloud-aarch64) meanwhile. But it is just temporary solution from my point of view, all architectures should be in one repository I think. It is not so big problem that you don't have 64 bit phone yet, when it compiles, it works usually :-) And you have big group of loyal testers, including me.

**Comment by fredldotme** [comment]
It's just that I'm doing so much work at the moment, from working on Ubuntu Touch to porting QML Creator and GhostCloud to Apple platforms.
I just don't know if I have the time to continue working on the SfOS part of GhostCloud for now, so I'm looking for someone who would like to join the GhostCloud team. :)

**Comment by fredldotme** [comment]
@Karry btw, would you allow me to relicense your changes to `src/common` as LGPLv2.1?
I plan to release some variant of GhostCloud to Apple platforms, which are only compatible to LGPLv2.1.

**Comment by Karry** [comment]
No problem, I am fine with LGPLv2.1 license :-) I am just curious, GPL-licensed applications cannot be distributed for Apple?

**Comment by fredldotme** [comment]
The GPLv2 and v3 allow certain freedoms that the Mac App Store would prevent you from making use of. LGPLv2.1 is fine though, at least VLC seems to have succeeded with that.

And thanks for relicensing that part of your work :)

**Pull request merged**
